import 'package:fezs_shopkeeper/bean/genater.dart';
import 'package:fezs_shopkeeper/bean/man.dart';
import 'package:fezs_shopkeeper/bean/user.dart';
import 'package:fezs_shopkeeper/mixin/toast_mixin.dart';
import 'package:fezs_shopkeeper/redux/app.dart';
import 'package:fezs_shopkeeper/utils/js_receive_manager.dart';
import 'package:flutter/material.dart';
import 'package:flutter_redux/flutter_redux.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:multi_image_picker/multi_image_picker.dart';
import 'dart:convert' as convert;

class CustomerManagementPage extends StatefulWidget {
  @override
  _CustomerManagementPageState createState() => _CustomerManagementPageState();
}

class _CustomerManagementPageState extends State<CustomerManagementPage>
    with AutomaticKeepAliveClientMixin, ToastMixin {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("客户管理"),
        centerTitle: true,
      ),
      body: StoreProvider(
        store: store,
        child: StreamBuilder(
            stream: null,
            builder: (context, snapdate) {
              return GestureDetector(
                onTap: () {
                  
                  Autogenerated autogenerated = Autogenerated(type: 1001);
                  Data data = Data(stat: "aaaa");
                  autogenerated.data = data;

                  showToast(convert.jsonEncode(autogenerated));
                  JsReceiveManager.getInstance().receiveMsg(convert.jsonEncode(autogenerated));
                },
                child: Center(
                  child: Text("客户管理"),
                ),
              );
            }),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}
